buildscript {
	repositories {
		mavenCentral()
	}

	ext {
		flywaydbPostgresPlugin = "13.4.0"
	}

	dependencies {
		classpath "org.flywaydb:flyway-database-postgresql:$flywaydbPostgresPlugin"
	}
}

plugins {
    id "java"
	id "org.flywaydb.flyway" version "13.4.0"
}

group = 'ru.strawberry'
version = '0.0.1-SNAPSHOT'

repositories {
	mavenCentral()
}

ext {
	telegramBotsVersion = "6.9.7.1"
	redisVersion = "5.2.0"
	springCoreVesion = "7.0.5"
	slf4Version = "2.0.16"
	lombokVersion = "1.18.38"
}

dependencies {
//	implementation "org.springframework:spring-core:$springCoreVesion"
//	implementation "org.springframework:spring-context:$springCoreVesion"
	implementation project(":board-game-app-web-unit")
	implementation "redis.clients:jedis:$redisVersion"
	implementation "org.telegram:telegrambots:$telegramBotsVersion"


	compileOnly "org.projectlombok:lombok:$lombokVersion"
	annotationProcessor "org.projectlombok:lombok:$lombokVersion"
}

flyway {
	url = "${System.env.FLYWAY_URL}"
	user = "${System.env.FLYWAY_USER}"
	password = "${System.env.FLYWAY_PASSWORD}"
	schemas = ["${System.env.FLYWAY_SCHEMA}"]
	placeholders = ["current_schema": "${System.env.FLYWAY_CURRENT_SCHEMA}"]
}

apply from: "flyway/settings-flyway.gradle"

jar {
	manifest {
		attributes "Main-Class": "ru.strawberry.boardgame.Application"
	}
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE

	from {
		configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
	}
}

subprojects {

	apply plugin: 'java'

	dependencies {
		// Main source set
		compileOnly "org.projectlombok:lombok:$lombokVersion"

//		implementation "org.slf4j:slf4j-api:$slf4Version"
//		implementation "org.slf4j:slf4j-simple:$slf4Version"

		annotationProcessor "org.projectlombok:lombok:$lombokVersion"
	}
}
