plugins {
    id "java"
	id "org.flywaydb.flyway" version "9.0.4"
}

group = 'ru.strawberry'
version = '0.0.1-SNAPSHOT'

repositories {
	mavenCentral()
}

ext {
	telegramBotsVersion = "6.9.7.1"
	jacksonVersion = "2.18.2"
	redisVersion = "5.2.0"
	hibernateVersion = "5.6.15.Final"
	postgresqlVersion = "42.7.3"
	springCoreVesion = "7.0.5"
	springBootVesion = "4.0.5"
}

dependencies {
//	implementation "org.springframework:spring-core:$springCoreVesion"
//	implementation "org.springframework:spring-context:$springCoreVesion"
	implementation "org.springframework.boot:spring-boot:$springBootVesion"
	implementation "org.hibernate:hibernate-core:$hibernateVersion"
	implementation "org.postgresql:postgresql:$postgresqlVersion"
	implementation "com.fasterxml.jackson.core:jackson-databind:$jacksonVersion"
	implementation "redis.clients:jedis:$redisVersion"
	implementation "org.slf4j:slf4j-api:2.0.16"
	implementation "org.slf4j:slf4j-simple:2.0.16"
	implementation "org.telegram:telegrambots:$telegramBotsVersion"


	compileOnly "org.projectlombok:lombok:1.18.22"
	annotationProcessor "org.projectlombok:lombok:1.18.22"
}

flyway {
	url = "${System.env.FLYWAY_URL}"
	user = "${System.env.FLYWAY_USER}"
	password = "${System.env.FLYWAY_PASSWORD}"
	schemas = ["${System.env.FLYWAY_SCHEMA}"]
	placeholders = ["current_schema": "${System.env.FLYWAY_CURRENT_SCHEMA}"]
}

apply from: "flyway/dev-flyway.gradle"

jar {
	manifest {
		attributes "Main-Class": "ru.strawberry.boardgame.Application"
	}
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE

	from {
		configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
	}
}
