bot.token=1909368048:AAEI2tcuBXGRmNmOzkFiLOur_08AFA8XK9A

tesera.url=https://api.tesera.ru

datasource.url=jdbc:postgres//localhost:9006/party_sd
datasource.username=party_sd_admin
datasource.password=w@nna_party

redis.url=http://158.160.233.25
redis.port=6380